### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by kudumi** [tompreston/MPD-Web-Remote#2]
I have no idea I can't connect to mpd. I have few other clients like npc and web clients like MPD-Webinterface. They all work great; no connection issue. But why I can't connect MPD-Web-Remote to mpd?

**Comment by kudumi** [comment]
it's working now. (I did reinstall, I don't know what was wrong before)

**Comment by tswaehn** [comment]
So Great You solved that,... :)

**Comment by kudumi** [comment]
yes! something went wrong while I installed first time.

thanks
